version: '3'
services:

  is.seanmorr.subspace-terminal.web:
    build:
      context: ../
      dockerfile: infra/app.Dockerfile
    image: seanmorris/subspace-terminal-web
    restart: always
    ports:
      - "80:80"
    volumes:
      - ../:/app
    depends_on:
      - is.seanmorr.subspace-terminal.database

  is.seanmorr.subspace-terminal.socket:
    build:
      context: ../
      dockerfile: infra/socket.Dockerfile
    image: seanmorris/subspace-terminal-socket
    restart: always
    ports:
      - "9998:9998"
    volumes:
      - ../:/app
    depends_on:
      - is.seanmorr.subspace-terminal.database
    
  is.seanmorr.subspace-terminal.database:
    image: mysql:5.7
    restart: always
    ports:
      - "9896:3306"
    volumes:
      - is.seanmorr.subspace-terminal.schema:/var/lib/mysql
    environment:
      MYSQL_USER:          'subspace-terminal'
      MYSQL_DATABASE:      'subspace-terminal'
      MYSQL_PASSWORD:      'password'
      MYSQL_ROOT_PASSWORD: 'supersecret'
    command: ['mysqld', '--character-set-server=utf8mb4']

  is.seanmorr.subspace-terminal.worker:
    build:
      context: ../
      dockerfile: infra/worker.Dockerfile
    image: seanmorris/subspace-terminal-worker
    restart: on-failure
    volumes:
      - ../:/app
    depends_on:
      - is.seanmorr.subspace-terminal.database

  is.seanmorr.subspace-terminal.updater:
    build:
      context: ../
      dockerfile: infra/updater.Dockerfile
    image: seanmorris/subspace-terminal-updater
    restart: on-failure
    volumes:
      - ../:/app
    depends_on:
      - is.seanmorr.subspace-terminal.database

  is.seanmorr.subspace-terminal.watcher:
    build:
      context: ../
      dockerfile: infra/watcher.Dockerfile
    image: seanmorris/subspace-terminal-watcher
    restart: always
    ports:
      - "9485:9485"
      - "3333:3333"
    volumes:
      - ../:/app

volumes:
  is.seanmorr.subspace-terminal.schema:
    driver: "local"
