version: '3'

services:
  
  app.subspace.seanmorr.is:
    build:
      context: ../
      dockerfile: infra/app.Dockerfile
    image: r.cfcr.io/seanmorris/app.subspace.seanmorr.is
    restart: always
    ports:
      - "80:80"
    volumes:
      - ../:/app
    depends_on:
      - database.subspace.seanmorr.is

  worker.subspace.seanmorr.is:
    build:
      context: ../
      dockerfile: infra/worker.Dockerfile
    image: r.cfcr.io/seanmorris/worker.seanmorr.is
    restart: on-failure
    volumes:
      - ../:/app
    depends_on:
      - database.subspace.seanmorr.is

  socket.subspace.seanmorr.is:
    build:
      context: ../
      dockerfile: infra/socket.Dockerfile
    image: r.cfcr.io/seanmorris/socket.subspace.seanmorr.is
    restart: always
    ports:
      - "9998:9998"
    volumes:
      - ../:/app
    depends_on:
      - database.subspace.seanmorr.is

  updater.seanmorr.is:
    build:
      context: ../
      dockerfile: infra/updater.Dockerfile
    image: r.cfcr.io/seanmorris/updater.seanmorr.is
    restart: on-failure
    volumes:
      - ../:/app
    depends_on:
      - database.subspace.seanmorr.is
    
  database.subspace.seanmorr.is:
    image: mysql:5.7
    restart: always
    ports:
      - "9996:3306"
    volumes:
      - schema.subspace.seanmorr.is:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'supersecret'
      MYSQL_USER: 'subspace'
      MYSQL_PASSWORD: 'password'
      MYSQL_DATABASE: 'subspace'
    command: ['mysqld', '--character-set-server=utf8mb4']

  # watcher.seanmorr.is:
  #   build:
  #     context: ../
  #     dockerfile: infra/watcher.Dockerfile
  #   image: watcher.seanmorr.is
  #   restart: always
  #   ports:
  #     - "9485:9485"
  #     - "3333:3333"
  #   volumes:
  #     - ../:/app

volumes:
  schema.subspace.seanmorr.is:
    driver: "local"
