version: '3'
services:

  web:
    build:
      context: ../../
      dockerfile: ${ROOTDIR}/infra/docker/app.Dockerfile
    image: seanmorris/subspace-terminal-web
    restart: always
    user: "${UID}:${GID}"
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ${ROOTDIR}/:/app
    depends_on:
      - database
    env_file:
      - ${MAIN_DLT}
      - ${MAIN_ENV}
      - ${TRGT_DLT}
      - ${TRGT_ENV}

  socket:
    build:
      context: ../../
      dockerfile: ${ROOTDIR}/infra/docker/socket.Dockerfile
      args:
        ROOTDIR: ${OUTROOTDIR}
    image: seanmorris/subspace-terminal-socket
    restart: always
    user: "${UID}:${GID}"
    ports:
      - "9998:9998"
    volumes:
      - ${ROOTDIR}/:/app
    depends_on:
      - database
    env_file:
      - ${MAIN_DLT}
      - ${MAIN_ENV}
      - ${TRGT_DLT}
      - ${TRGT_ENV}

  database:
    image: mysql:5.7
    restart: always
    ports:
      - "9896:3306"
    volumes:
      - schema:/var/lib/mysql
    environment:
      MYSQL_USER:          'subspace-terminal'
      MYSQL_DATABASE:      'subspace-terminal'
      MYSQL_PASSWORD:      'password'
      MYSQL_ROOT_PASSWORD: 'supersecret'
    command: ['mysqld', '--character-set-server=utf8mb4']

  worker:
    build:
      context: ../../
      dockerfile: ${ROOTDIR}/infra/docker/worker.Dockerfile
    image: seanmorris/subspace-terminal-worker
    restart: on-failure
    volumes:
      - ${ROOTDIR}/:/app
    depends_on:
      - database

  watcher:
    build:
      context: ../../
      dockerfile: ${ROOTDIR}/infra/docker/watcher.Dockerfile
    image: seanmorris/subspace-terminal-watcher
    ports:
      - "9485:9485"
      - "3333:3333"
    volumes:
      - ${ROOTDIR}/:/app
    env_file:
      - ${ROOTDIR}/.env
      - ${ROOTDIR}/.lock_env

  rabbit:
    image: "rabbitmq:3-management"
    restart: always
    environment:
      RABBITMQ_ERLANG_COOKIE: "O234234QALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "19994:15672"
      - "9994:5672"
    volumes:
      - ${ROOTDIR}/data/global/rabbitMq/enabled_plugins:/etc/rabbitmq/enabled_plugins

  # composer:
  #   build:
  #     context: ../../
  #     dockerfile: ${ROOTDIR}/infra/docker/composer.Dockerfile
  #   image: seanmorris/subspace-terminal-composer
  #   restart: on-failure
  #   volumes:
  #     - ${ROOTDIR}/:/app
  #     - ${ROOTDIR}/data/local/composer/:/root/.composer/

  certbot:
    user: "${UID}:${GID}"
    image:   certbot/certbot
    command: ls
    volumes:
      - ../../data/local/certbot:/etc/letsencrypt/

  # fakecert:
  #   image: vishnunair/docker-mkcert:latest
  #   environment:
  #     domain: localhost
  #   volumes:
  #     - ../data/local/certbot/subspace2.seanmorr.is:/root/.local/share/mkcert

volumes:
  schema:
    driver: "local"
